const Configuration = {
    GAME_WIDTH: 800,
    GAME_HEIGHT: 400,
    GAME_RENDER_ID: 'game',

    SEARCHING_PLAYER_SPEED: 300,
    SEARCHING_MAPS_TIME_LIMIT: [13, 11, 9],

    FIGHT_GRAVITY: 10,
    FIGHT_BOTTOM_MARGIN: 40,
    FIGHT_PLAYER_SPEED: 300,
    FIGHT_PLAYER_JUMP: 500,
    FIGHT_CHARACTER_AVATAR_WIDTH: 50,
    FIGHT_CHARACTER_AVATAR_HEIGHT: 70,
    FIGHT_KICKING_POINTS: 10,
    FIGHT_BOXING_POINTS: 5,
    FIGHT_MAX_EXP: 100,
    FIGHT_MAX_LVL: 100,
    FIGHT_LVL_FIRST_THRESHOLD: 30,
    FIGHT_LVL_SECOND_THRESHOLD: 60
};

export default Configuration;
